
server:
  port: 8080
spring:
  application:
    name: sharding-springboot-mybatis
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: shardingjdbc.dao

sharding:
  jdbc:
    datasource:
      names: ds0,ds1,ds2
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.0.6.141:3306/test_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.0.6.141:3306/test_order2?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.0.6.141:3306/test_order3?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:
            key-generator-column-name: id
            actual-data-nodes: ds${0..2}.t_user${0..1}
            database-strategy:
              inline:
                sharding-column: city_id
                algorithm-expression: ds${city_id % 3}
            table-strategy:
              inline:
                sharding-column: sex
                algorithm-expression: t_user${sex % 3}
          t_address:
            key-generator-column-name: id
            actual-data-nodes: ds${0..2}.t_address
            database-strategy:
              inline:
                sharding-column: lit
                algorithm-expression: ds${lit % 3}
